#!/bin/sh

# Set our values for PCDM
export PICO_CLIENT_LOGIN=$(whoami)
export PICO_CLIENT_HOME="${HOME}"

# Create any pulseaudio settings
if [ -e "${HOME}/pcookie" ]; then
  echo "Enabling PULSEAUDIO..."
  export PICO_PULSE_COOKIE="${PICO_CLIENT_HOME}/pcookie"
  export PULSE_SERVER="`echo ${SSH_CONNECTION} | cut -d ' ' -f 1`"
fi

cd $HOME
chmod 660 .Xauthority

sudo -E /usr/local/bin/PCDM-session

echo "Killing SSH login..."
ps -auwwx | grep 'sshd' | grep "$PICO_CLIENT_LOGIN@notty" | awk '{print $2}' | xargs kill -9

exit 0
